theme: jekyll-theme-minimal

baseurl: https://rjwood11.github.io/TMDL/

publishdir: ../myblog

title: R blog TMDL

menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/rstudio/blogdown
    - name: Twitter
      url: https://twitter.com/rstudio